### PR TITLE
added missing piece to make minimal space work, and set default setting ...

### PR DESCRIPTION
**Pull request by vegansupreme**
...to 0.

### CODE REVIEW

**Comment by killua99** [comment]
Looks nice.

I guess I'll remove the align of equals so we have a "standard"

**Comment by vegansupreme** [comment]
Oh I see what you mean. Want me to align it to the existing, or remove the old alignment?

**Comment by vegansupreme** [comment]
I adjusted spacing to line up the equals.

**Comment by killua99** [comment]
Alright, thanks mate. :+1:

**Pull request merged**
